name: Link Branch to Issue

on:
  push:
    branches:
      - 'feat/*'

permissions:
  issues: write  # Permite atualizar issues
  pull-requests: write  # Opcional, para PRs

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number from Branch Name
        id: extract
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oE '[0-9]+')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
      - name: Link Branch to Issue
        if: env.ISSUE_NUMBER != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = process.env.ISSUE_NUMBER;
            const branchName = '${{ github.ref_name }}';
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              development: { sha: '${{ github.sha }}', ref: branchName }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}