name: Move Issue to In Progress

on:
  issues:
    types: [opened, reopened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to In Progress
        uses: actions/github-script@v7
        with:
          script: |
            const query = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $value: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $value
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;

            // Replace these with your actual values
            const projectId = "YOUR_PROJECT_ID";
            const itemId = context.payload.issue.node_id;
            const fieldId = "YOUR_STATUS_FIELD_ID";
            const inProgressOptionId = "YOUR_IN_PROGRESS_OPTION_ID";

            await github.graphql(query, {
              projectId,
              itemId,
              fieldId,
              value: inProgressOptionId
            });