name: Atualizar Status da Issue para In Progress (sem gh CLI)

on:
  create:
    branches:
      - '**'

jobs:
  update_issue_status:
    runs-on: ubuntu-latest

    env:
      GITHUB_API: https://api.github.com/graphql
      AUTH_TOKEN: ${{ secrets.DDDBankSecret }} 

    steps:
      - name: Extrair número da issue da branch
        id: extract
        run: |
          if [[ "${{ github.ref_name }}" =~ .*/([0-9]+)_.* ]]; then
            echo "ISSUE_NUMBER=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "matched=true"       >> $GITHUB_ENV
          else
            echo "matched=false"      >> $GITHUB_ENV
          fi

      - name: Abortar se não for branch de issue
        if: env.matched != 'true'
        run: echo "Branch sem número de issue. Saindo..."

      - name: Obter dados do ProjectV2
        if: env.matched == 'true'
        run: |
          read -r -d '' QUERY << 'EOF'
          query {
            viewer {
              projectV2(number: 4) {
                id
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options { id name }
                    }
                  }
                }
              }
            }
          }
          EOF

          curl -s -X POST "$GITHUB_API" \
            -H "Authorization: bearer $AUTH_TOKEN" \
            -d "{\"query\":$(jq -Rs . <<< \"$QUERY\")}" \
            > project.json

          export PROJECT_ID=$(jq -r .data.viewer.projectV2.id project.json)
          export STATUS_FIELD_ID=$(jq -r '.data.viewer.projectV2.fields.nodes[] | select(.name=="Status") | .id' project.json)
          export IN_PROGRESS_OPTION_ID=$(jq -r '.data.viewer.projectV2.fields.nodes[] | select(.name=="Status") | .options[] | select(.name=="In Progress") | .id' project.json)

          echo "PROJECT_ID=$PROJECT_ID"       >> $GITHUB_ENV
          echo "STATUS_FIELD_ID=$STATUS_FIELD_ID" >> $GITHUB_ENV
          echo "IN_PROGRESS_OPTION_ID=$IN_PROGRESS_OPTION_ID" >> $GITHUB_ENV

      - name: Obter node ID da issue
        if: env.matched == 'true'
        run: |
          read -r -d '' QUERY << 'EOF'
          query($owner:String!,$repo:String!,$num:Int!) {
            repository(owner:$owner,name:$repo) {
              issue(number:$num) {
                id
              }
            }
          }
          EOF

          ISSUE_ID=$(curl -s -X POST "$GITHUB_API" \
            -H "Authorization: bearer $AUTH_TOKEN" \
            -d "{\"query\":$(jq -Rs . <<< \"$QUERY\"),\"variables\":$(jq -n --arg owner "${{ github.repository_owner }}" \
                                                                       --arg repo  "${{ github.event.repository.name }}" \
                                                                       --argjson num $ISSUE_NUMBER \
                                                                       '{owner:$owner,repo:$repo,num:$num}')}\
            " | jq -r .data.repository.issue.id)

          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Localizar item do ProjectV2 para a issue
        if: env.matched == 'true'
        run: |
          read -r -d '' QUERY << 'EOF'
          query($proj:ID!) {
            node(id:$proj) {
              ... on ProjectV2 {
                items(first:100) {
                  nodes {
                    id
                    content { __typename ... on Issue { id } }
                  }
                }
              }
            }
          }
          EOF

          ITEM_ID=$(curl -s -X POST "$GITHUB_API" \
            -H "Authorization: bearer $AUTH_TOKEN" \
            -d "{\"query\":$(jq -Rs . <<< \"$QUERY\"),\"variables\":$(jq -n --arg proj "$PROJECT_ID" '{proj:$proj}')}\
            " | jq -r --arg iid "$ISSUE_ID" \
                '.data.node.items.nodes[] | select(.content.id==$iid) | .id')

          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV

      - name: Atualizar Status para In Progress
        if: env.ITEM_ID
        run: |
          read -r -d '' MUTATION << 'EOF'
          mutation($proj:ID!,$item:ID!,$field:ID!,$opt:String!) {
            updateProjectV2ItemFieldValue(input:{
              projectId:$proj,
              itemId:$item,
              fieldId:$field,
              value:{ singleSelectOptionId:$opt }
            }) {
              projectV2Item { id }
            }
          }
          EOF

          curl -s -X POST "$GITHUB_API" \
            -H "Authorization: bearer $AUTH_TOKEN" \
            -d "{\"query\":$(jq -Rs . <<< \"$MUTATION\"),\"variables\":$(jq -n \
              --arg proj "$PROJECT_ID" \
              --arg item "$ITEM_ID" \
              --arg field "$STATUS_FIELD_ID" \
              --arg opt "$IN_PROGRESS_OPTION_ID" \
              '{proj:$proj,item:$item,field:$field,opt:$opt}')}" \
            > response.json

          echo "Issue #$ISSUE_NUMBER movida para In Progress."
